version: '3'

services:
  postgresql:
    container_name: postgresql
    image: "postgres:14.4"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=file-loader
