spring:
  application:
    name: file-loader
  webflux:
    base-path: /${spring.application.name}
  profiles:
    active: dev
  data:
    r2dbc:
      repositories:
        enabled: true
  r2dbc:
    password: admin
    username: admin
    url: r2dbc:postgresql://localhost:5432/file-loader
    pool:
      enabled: true
      initial-size: 5
      max-idle-time: PT10M
      max-size: 10
  liquibase:
    enabled: true
    url: jdbc:postgresql://localhost:5432/file-loader
    user: admin
    password: admin
    change-log: classpath:/changelog/changelog-master.yml

server:
  servlet:
    context-path: /${spring.application.name}
  port: 8080

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] [%mdc] %-5level %logger{40} - %msg%n'
  appender:
    name: STDOUT
