create table if not exists file
(
    id           bigint generated by default as identity constraint file_pk primary key,
    url          varchar(255) not null,
    size         integer      not null,
    content_type varchar(100) not null,
    content      bytea        not null
    );

create table if not exists summary
(
    files_count integer not null,
    files_size  bigint  not null
);

insert into summary (files_count, files_size) values (0, 0);
